version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 14.21.3
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_6Mu3vA0y
      - echo Setting up SonarQube scanner...
      - export SONAR_TOKEN=squ_a27cc0154f8c676964d974bd513d8094459a6220 # replace with your SonarQube token or pass it as an environment variable
      - export SONAR_PROJECT_KEY=test_sonaraws # replace with your SonarQube project key
      - export SONAR_HOST_URL=http://35.223.99.191:9000 # replace with your SonarQube server URL
      - echo Running SonarQube analysis...
      - npx sonar-scanner -D"sonar.projectKey=${SONAR_PROJECT_KEY}" -D"sonar.host.url=${SONAR_HOST_URL}" -D"sonar.login=${SONAR_TOKEN}" -X
      - echo Creating tar.gz archive of build files...
      - cd build
      - tar -czvf ../PLN6000155.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN6000155.tar.gz

