version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting Docker build phase...
      - IMAGE_TAG=test-$(date +%s)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-react-app:$IMAGE_TAG .

  post_build:
    commands:
      - echo Docker image my-react-app:$IMAGE_TAG built successfully.

artifacts:
  files:
    - '**/*'

