version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 22.14.0
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_7gs9etsx
      - echo Creating tar.gz archive of build files...
      - cd build
      - tar -czvf ../PLN1000035.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN1000035.tar.gz
