version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 14.21.3
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_pdPvEBM4
      - echo Creating tar.gz archive of build files...
      - cd build
      - tar -czvf ../PLN6000358.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN6000358.tar.gz
