phases:
  install:
    runtime-versions:
      nodejs: 14.21.3
    commands:
      - echo Installing dependencies...
      - npm install --force
      - echo Installing unzip utility...
      - yum install -y unzip
      - echo Downloading SonarQube Scanner...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin

  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose

  build:
    commands:
      - echo Running SonarQube analysis...
      - export SONAR_PROJECT_KEY=sonar_test_aws
      - export SONAR_TOKEN=squ_a27cc0154f8c676964d974bd513d8094459a6220
      - export SONAR_HOST_URL=http://35.223.99.191:9000
      - sonar-scanner -D"sonar.projectKey=${SONAR_PROJECT_KEY}" -D"sonar.host.url=${SONAR_HOST_URL}" -D"sonar.login=${SONAR_TOKEN}" -X
      - echo Creating tar.gz archive of build files...
      - cd build
      - tar -czvf ../PLN6000155.tar.gz *

  post_build:
    commands:
      - echo Pushing artifacts...

artifacts:
  files:
    - PLN6000155.tar.gz
