options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Cloning the repository..."
                  echo "ID_eoaCOSjm"
                  git config --global credential.helper 'store --file=/root/.git-credentials'
                  echo "https://${_GITHUB_PAT}:@github.com/${_GITHUB_USERNAME}/${_GITHUB_REPO}" > /root/.git-credentials
                  git clone -b ${_BRANCH_NAME} https://github.com/${_GITHUB_USERNAME}/${_GITHUB_REPO}
  - name: 'node:18.20.4'
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Installing dependencies..."
                  cd ${_REPO_NAME}
                  npm install --force
  - name: 'node:18.20.4'
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Building project..."
                  cd ${_REPO_NAME}
                  npm run build --verbose
  - name: 'node:18.20.4'
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Node.js version:"
                  node -v
  - name: 'node:18.20.4'
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Creating tar.gz archive of build files..."
                  if [ -d ${_REPO_NAME}/build ]; then
                    cd ${_REPO_NAME}/build
                    tar -czvf ../${_ARTIFACT_NAME} *
                    echo "Tar file created at: $(pwd)/../${_ARTIFACT_NAME}"
                  else
                    echo "Error: Build directory does not exist."
                    exit 1
                  fi
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |-
        echo "Uploading tar.gz archive to Google Cloud Storage..."
                  gsutil cp ${_REPO_NAME}/${_ARTIFACT_NAME} gs://${_BUCKET_NAME}/${_PIPELINE_NAME}/${_VERSION}/${_ARTIFACT_NAME}
                  echo "Uploaded tar.gz archive to Google Cloud Storage..."
