trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*'
variables:
  Devozy_DUMMY_VARIABLE: ID_htbhejTM
  IMAGE_NAME: PLN6000156_MERN_UAT
pool:
  vmImage: ubuntu-latest
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.21.3
    displayName: node
  - script: npm install --legacy-peer-deps
    displayName: npm
  - script: npm run build
    displayName: npm build
  - script: cd build;sudo tar -czvf pln6000156.tar.gz *;mv pln6000156.tar.gz ..
    displayName: Create tar.gz Archive of Build Files
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)/pln6000156.tar.gz
      artifactName: react-build
